RubyOnRails_WebApp/supplier/config/routes.rb
Rails.application.routes.draw do

  resources :wine_bottles

  # match incoming orders...
  match 'order_receiver/receive_order' => 'order_receiver_controller/receive_order', :via => [:post]

end

RubyOnRails_WebApp/supplier/app/models/wine_bottle.rb
class WineBottle < ActiveRecord::Base
end

RubyOnRails_WebApp/supplier/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

RubyOnRails_WebApp/supplier/app/controllers/order_receiver_controller.rb
class OrderReceiverController < ApplicationController

  def receive_order
    puts 'Received order !'
    puts params[:the_order]
  end

end

RubyOnRails_WebApp/supplier/app/controllers/wine_bottles_controller.rb
class WineBottlesController < ApplicationController
  before_action :set_wine_bottle, only: [:show, :edit, :update, :destroy]

  # GET /wine_bottles
  # GET /wine_bottles.json
  def index
    @wine_bottles = WineBottle.all
    fresh_when @wine_bottles
  end

  # GET /wine_bottles/1
  # GET /wine_bottles/1.json
  def show
    fresh_when @wine_bottle
  end

  # GET /wine_bottles/new
  def new
    @wine_bottle = WineBottle.new
  end

  # GET /wine_bottles/1/edit
  def edit
  end

  # POST /wine_bottles
  # POST /wine_bottles.json
  def create
    @wine_bottle = WineBottle.new(wine_bottle_params)

    respond_to do |format|
      if @wine_bottle.save
        format.html { redirect_to @wine_bottle, notice: 'Wine bottle was successfully created.' }
        format.json { render :show, status: :created, location: @wine_bottle }
      else
        format.html { render :new }
        format.json { render json: @wine_bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wine_bottles/1
  # PATCH/PUT /wine_bottles/1.json
  def update
    respond_to do |format|
      if @wine_bottle.update(wine_bottle_params)
        format.html { redirect_to @wine_bottle, notice: 'Wine bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine_bottle }
      else
        format.html { render :edit }
        format.json { render json: @wine_bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wine_bottles/1
  # DELETE /wine_bottles/1.json
  def destroy
    @wine_bottle.destroy
    respond_to do |format|
      format.html { redirect_to wine_bottles_url, notice: 'Wine bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine_bottle
      @wine_bottle = WineBottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_bottle_params
      params.require(:wine_bottle).permit(:supplier, :image_url, :description, :country, :grape, :vegeterians_suitable, :size, :price, :avin)
    end
end

RubyOnRails_WebApp/supplier/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails_WebApp/supplier/app/helpers/order_receiver_helper.rb
module OrderReceiverHelper
end

RubyOnRails_WebApp/supplier/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supplier01</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

RubyOnRails_WebApp/supplier/app/views/wine_bottles/_form.html.erb
<%= form_for(@wine_bottle) do |f| %>
  <% if @wine_bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine_bottle.errors.count, "error") %> prohibited this wine_bottle from being saved:</h2>

      <ul>
      <% @wine_bottle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :grape %><br>
    <%= f.text_field :grape %>
  </div>
  <div class="field">
    <%= f.label :vegeterians_suitable %><br>
    <%= f.check_box :vegeterians_suitable %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
    <div class="field">
    <%= f.label :avin %><br>
    <%= f.text_field :avin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RubyOnRails_WebApp/supplier/app/views/wine_bottles/edit.html.erb
<h1>Editing Wine Bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine_bottle %> |
<%= link_to 'Back', wine_bottles_path %>

RubyOnRails_WebApp/supplier/app/views/wine_bottles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wine Bottles</h1>

<table>
  <thead>
    <tr>
      <th>supplier</th>
      <th>Image url</th>
      <th>Description</th>
      <th>Country</th>
      <th>Grape</th>
      <th>Vegeterians suitable</th>
      <th>Size</th>
      <th>Price</th>
      <th>AVIN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wine_bottles.each do |wine_bottle| %>
      <tr>
        <td><%= wine_bottle.supplier %></td>
        <td><%= wine_bottle.image_url %></td>
        <td><%= wine_bottle.description %></td>
        <td><%= wine_bottle.country %></td>
        <td><%= wine_bottle.grape %></td>
        <td><%= wine_bottle.vegeterians_suitable %></td>
        <td><%= wine_bottle.size %></td>
        <td><%= wine_bottle.price %></td>
        <td><%= wine_bottle.avin %></td>
        <td><%= link_to 'Show', wine_bottle %></td>
        <td><%= link_to 'Edit', edit_wine_bottle_path(wine_bottle) %></td>
        <td><%= link_to 'Destroy', wine_bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine bottle', new_wine_bottle_path %>

RubyOnRails_WebApp/supplier/app/views/wine_bottles/new.html.erb
<h1>New Wine Bottle</h1>

<%= render 'form' %>

<%= link_to 'Back', wine_bottles_path %>

RubyOnRails_WebApp/supplier/app/views/wine_bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>supplier:</strong>
  <%= @wine_bottle.supplier %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @wine_bottle.image_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wine_bottle.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @wine_bottle.country %>
</p>

<p>
  <strong>Grape:</strong>
  <%= @wine_bottle.grape %>
</p>

<p>
  <strong>Vegeterians suitable:</strong>
  <%= @wine_bottle.vegeterians_suitable %>
</p>

<p>
  <strong>Size:</strong>
  <%= @wine_bottle.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wine_bottle.price %>
</p>

<p>
  <strong>AVIN:</strong>
  <%= @wine_bottle.avin %>
</p>

<%= link_to 'Edit', edit_wine_bottle_path(@wine_bottle) %> |
<%= link_to 'Back', wine_bottles_path %>