RubyOnRails_WebApp/MAF/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :basket_items, only: [:create]
  resources :baskets, only: [:destroy]

  get 'store/index'
  get 'store/check_out'
  get 'store/search', to: 'store#search', as: 'search'
  get 'store/:avin', to: 'store#show', as: 'show'
  get 'store/show'

  root 'store#index'
  get '*path' => redirect('/')

end

RubyOnRails_WebApp/MAF/app/models/basket.rb
class Basket < ActiveRecord::Base
  has_many(:basket_items, dependent: :destroy)

  def add_basket_item(avin, price, quantity, supplier)
    current_item = basket_items.find_by(avin: avin)
    if current_item
      current_item.quantity += quantity
    else
      current_item = basket_items.
          build(avin: avin, price: price, quantity: quantity, supplier: supplier)
    end
    current_item
  end

  def total_price
    basket_items.to_a.sum { |item| item.total_price }
  end
end

RubyOnRails_WebApp/MAF/app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

=begin
  Destroys the current basket information, along with the associated basket items.
  Thread is used to make things a bit more fluid for the user
=end
  def destroy
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.js {}
    end

    Thread.new do
      @basket.destroy if @basket.id == session[:basket_id]
      session[:basket_id] = nil
    end
  end

end

RubyOnRails_WebApp/MAF/app/helpers/baskets_helper.rb
module BasketsHelper
end

RubyOnRails_WebApp/MAF/app/views/baskets/_basket.html.erb
<h2>Wines in basket</h2>

<% if basket.basket_items.length > 0 %>

    <table>

      <%= render :partial => '/basket_items/basket_item', :collection => basket.basket_items %>

      <tr class="total_line">
        <td colspan="2">Total</td>
        <td class="total_cell"><%= number_to_currency(basket.total_price, unit: '£') %></td>
      </tr>
    </table>
    <%= button_to 'Checkout', store_check_out_path, method: :get, class: 'btn btn-success' %>
    <%= button_to 'Empty Basket', @basket, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}, remote: true, :authenticity_token => true, id: :empty_basket %>
<% else %>
    <%= content_tag(:p, 'Basket empty') %>
<% end %>

RubyOnRails_WebApp/MAF/app/views/baskets/destroy.js.erb
$('#basket').hide('slow');

$('#notice')
    .hide('slow')
    .html("<%= escape_javascript(content_tag(:p, 'Basket emptied', class: :notice)) %>")
    .show('blind', 1000)
    .css({'display': 'default'});

RubyOnRails_WebApp/MAF/app/views/baskets/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<%= render @basket %>